#!/bin/sh
# This is my statusbar script for dwm, it display modules like the weather, uptime, date, time and even your battery life if you have a laptop.
# Every module is actually just a variable displayed with xsetroot
# You can change the date and time format to your liking.
# You should also change your location to your city to get correct weather forecasts
#
# The battery module finds your charging limit and calculates your effective battery life left.
# For example if you have a charging limit set at 80% it will convert your battery life back on a scale of 0-100%

# Emojis
uptime_emoji="🐧"
date_emoji="📆"
time_emoji="🕘"
music_emoji="🎧"
battery_emoji="🔌"
delimeter=" |"


# Weather variables
timer=1					# This timer will fetch new weather information once it reaches the desired updatetime
updatetime=3600				# This variable sets the updatetime for the weather in seconds, 3600 seconds equals 1 hour
location="angers"			# What city to get weather information about
weather="$(curl -s "https://wttr.in/$location?format=%c%C+%f" | sed 's/\(^.\)..\(.*\)/\1\2/')$delimeter"

while true
do
	# Modules are updated from left to right in the statusbar

	# You can't append the delimiter without sed here because it reads it like a pipe...
	song="$(ncmpcpp --quiet --current-song=' %20a - %25t '$music_emoji | sed "s/$/$delimeter/")"

	# Weather module
	if [ $timer -lt $updatetime ]; then
		timer=$((timer+1))
	else
		weather="$(curl wttr.in/$location?format="%C+%f")$delimeter"
		timer=1
	fi

	uptime="$uptime_emoji $(w | head -n1 | cut -c 10-100 | sed 's/,.*//g' | awk '{print $1" "$2" "$3}' | sed 's/\s*$//g')$delimeter"

	date="$date_emoji $(date +"%a %d/%m")$delimeter" 	# wed 28/07
	#	date="$(date +"%a %d/%m/%y")" 		# wed 28/07/2021
	#	date="$(date +"%a %e %b %y")" 		# wed 28 july 2021
	#	date="$(date +"%a, %b %d")" 		# wednesday, july 28

	time="$time_emoji $(date +"%H:%M")"		# 24h
	# time="$(date +"$timeemoji %h:%m:%s")"		# 24h with seconds
	# time="$(date +"$timeemoji %i:%m %p")" 	# 0-12 with a.m p.m

	# Battery module, has to come last
	if [ -f /sys/class/power_supply/BAT0/capacity ]
	then
		battery="$(cat /sys/class/power_supply/BAT0/capacity)"

		if [ -f /sys/class/power_supply/BAT0/charge_stop_threshold ]
		then
			maxcharge=""0."$(cat /sys/class/power_supply/BAT0/charge_stop_threshold | tr -d '[ ]')"
			coefficient="$(echo "scale=2; 1/"$maxcharge | bc)"
			battery="$battery_emoji $(echo $battery" * "$coefficient"/1" | bc)%$delimeter" # divide by 1 to get the scale to 0 lmao
		fi

		# Display our modules in the status bar
		xsetroot -name "$song $weather $battery $uptime $date $time "
	else
		xsetroot -name "$song $weather $uptime $date $time "
	fi

	sleep 1		# Update them every second
done
